name: config
root: ~/

windows:
  - nvim:
      root: ~/.config/nvim
      panes:
        - 

  - fish: 
      root: ~/.config/fish
      panes:
        -

  - tmux: 
      root: ~/.config/tmux
      panes: 
        - nvim tmux.conf

  - tmuxinator:
      root: ~/.config/tmuxinator
      panes: 
        - 

